- microservices/storageApi/helm/storage-api/templates/deployment.yaml
Note:  storage helm values.yaml already updated in PR #9
> Update helm to support both minio server and gateway

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- frontend/README.md
- microservices/forumApi/README.md
- microservices/policyApi/README.md
- microservices/requestApi/README.md
- microservices/storageApi/README.md
- microservices/validateApi/README.md
This PR updates the README files with updated and proper markdown syntax, as well as adding a Contributing and Code of Conduct.
> Update and standardize documentation

- frontend/src/modules/output-checker/components/dashboard/index.jsx
- frontend/src/modules/output-checker/components/request-card/index.jsx
- frontend/src/modules/output-checker/components/request/details.jsx
- frontend/src/modules/output-checker/components/request/files.jsx
- frontend/src/modules/output-checker/components/request/index.jsx
- frontend/src/modules/output-checker/components/request/nav.jsx
- frontend/src/modules/output-checker/components/request/sidebar.jsx
- frontend/src/modules/output-checker/components/request/styles.css
- frontend/src/modules/output-checker/containers/requests-nav.js
- frontend/src/modules/output-checker/reducer.js
Just a small maintenance commit with some ID/classname support for integration testing.
> Add ID's to missing areas of the OC app

- frontend/src/modules/requests/components/request/details.jsx
Downloading files as an exporter was unnecessarily disabled, this PR enables it.
> Add download button to the Requester interface.

- frontend/.eslintrc
- frontend/package.json
- frontend/src/modules/requests/actions.js
- frontend/src/modules/requests/components/request-form/form.jsx
- frontend/src/modules/requests/components/request/sidebar.jsx
- frontend/src/modules/requests/components/requests-list/index.jsx
- frontend/src/modules/requests/containers/requests-list.js
- frontend/src/modules/requests/reducer.js
Copy changes, mainly to the requester interface, based on feedback from test users. Also adds a new "Filter My Requests" button on the main list page.
> Copy Changes

- microservices/forumApi/db/model/topic.js
- microservices/requestApi/routes/v1/routes/requests.js
Updated some error messages, removed unique topic name requirement
> Updated some error messages, removed unique topic name requirement

- frontend/server/app.js
- frontend/server/routes/files.js
- frontend/src/components/app-bar/menu.jsx
- frontend/src/modules/data/actions.js
- frontend/src/modules/data/components/messages/index.jsx
- frontend/src/modules/data/containers/messages.js
- frontend/src/modules/data/reducer.js
- frontend/src/modules/data/sagas.js
- frontend/src/modules/output-checker/actions.js
- frontend/src/modules/output-checker/components/app/styles.css
- frontend/src/modules/output-checker/components/dashboard/index.jsx
- frontend/src/modules/output-checker/components/request/index.jsx
- frontend/src/modules/output-checker/components/request/nav.jsx
- frontend/src/modules/output-checker/components/request/sidebar.jsx
- frontend/src/modules/output-checker/components/request/styles.css
- frontend/src/modules/output-checker/components/search/index.jsx
- frontend/src/modules/output-checker/containers/requests-nav.js
- frontend/src/modules/output-checker/containers/requests.js
- frontend/src/modules/output-checker/reducer.js
Includes a bevy of fixes (see ticket #90 ) as well as 2 small fixes for missing `filetype`s when downloading and a replacement title for the document.
> Output Checker Enhancements

- frontend/package.json
- frontend/src/modules/requests/actions.js
- frontend/src/modules/requests/components/request/__tests__/sidebar.test.jsx
- frontend/src/modules/requests/components/request/sidebar.jsx
- frontend/src/modules/requests/containers/request-form.js
- frontend/src/modules/requests/containers/sidebar.js
- frontend/src/modules/requests/reducer.js
- frontend/src/modules/requests/sagas.js
- frontend/tests/globals.js
- frontend/tests/setup.js
- frontend/yarn.lock
Added new flow to the exporter sidebar to make it easier for users to use. Instead of a Withdraw button it has now been renamed to Edit, and if they accept that it'll be removed from output checking it'll be withdrawn behind the scenes and the edit dialog will open. Also added a Duplicate button for closed requests so a new similar request could be picked up again easily.
> Refactor Exporter Sidebar actions

- frontend/package.json
- frontend/src/components/loading/index.jsx
- frontend/src/modules/output-checker/components/request/sidebar.jsx
- frontend/src/modules/output-checker/containers/requests.js
- frontend/src/modules/requests/components/request-icon/index.jsx
- frontend/src/modules/requests/components/requests-list/index.jsx
- frontend/src/modules/requests/components/state-label/index.jsx
- frontend/src/modules/requests/containers/requests-list.js
- frontend/src/modules/requests/containers/search.js
- frontend/src/utils/index.js
Includes some small copy changes, fixes to the request status icon label, proper package name, a loading dialog that allows the table to be clickable when requests are being loaded.
> Minor UI Tweaks (Issue 97)

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/title/index.jsx
- frontend/src/modules/discussion/components/discussion/index.jsx
- frontend/src/modules/exporter/components/app/index.jsx
- frontend/src/modules/output-checker/components/app/index.jsx
- frontend/src/modules/output-checker/components/dashboard/index.jsx
- frontend/src/modules/output-checker/components/request/files.jsx
- frontend/src/modules/output-checker/components/request/index.jsx
- frontend/src/modules/requests/components/request/index.jsx
- frontend/src/modules/requests/components/requests-list/index.jsx
This PR adds `react-helmet` and a custom Title component to set the title of the document based on the component/route that is loaded. This makes the history/back button much more readable and helpful.
> Add dynamic document.titles

- ui_tests/Include/features/requester/proj_auto_approve.feature
- ui_tests/Include/scripts/groovy/test/ocwa/features/LoginStep.groovy
- ui_tests/Profiles/default.glbl
- ui_tests/Scripts/Requester/ProjAutoApproveTest/Script1556138858670.groovy
- ui_tests/Test Cases/Requester/ProjAutoApproveTest.tc
- ui_tests/Test Suites/CucumberSuite.ts
This new integration test expands test coverage to projects that have auto approve turned on
> Added an auto approval test for project that have auto approve turned on

- frontend/src/components/app-bar/menu.jsx
…othing to show.
If the user payload doesn't have `fullName` or `username` fallback to `email`. Hide the whole menu if there's nothing to show.
> Add username fallback for app-bar menu

- frontend/README.md
- frontend/config/default.json.example
- frontend/config/test.json.example
- frontend/entrypoint.sh
- frontend/helm/ocwa-frontend/templates/deployment.yaml
- frontend/helm/ocwa-frontend/values.yaml
- frontend/server/routes/auth.js
- helm/ocwa/values.yaml
Logout worked on the front end only, adding an `auth.logoutURL` takes the user to the KeyCloak logout URL to terminate the session proper.
- [x I have checked that unit tests pass locally with my changes
> Ensure logout works completely

- microservices/requestApi/README.md
- microservices/requestApi/auth/auth.js
- microservices/requestApi/config/default.json.example
- microservices/requestApi/db/model/request.js
- microservices/requestApi/entrypoint.sh
- microservices/requestApi/helm/request-api/templates/deployment.yaml
- microservices/requestApi/helm/request-api/values.yaml
- terraform/ocwa_frontend.tf
- terraform/ocwa_request_api.tf
- terraform/scripts/keycloak-setup.sh
- terraform/scripts/mongodb.tpl
Terraform config was missed for the reports feature.  Adding a "supervisor_1" user who is part of the "reports" group.
> Updates to support reports

- frontend/.eslintrc
- frontend/package-lock.json
- frontend/src/modules/download/components/requests/index.jsx
- frontend/src/modules/output-checker/components/request/details.jsx
- frontend/src/modules/output-checker/components/request/files.jsx
- frontend/src/modules/output-checker/components/request/index.jsx
- frontend/src/modules/output-checker/components/request/sidebar.jsx
- frontend/src/modules/output-checker/components/request/styles.css
- frontend/src/modules/output-checker/containers/request.js
- frontend/src/modules/output-checker/containers/requests.js
- frontend/src/modules/reports/components/main/head.jsx
- frontend/src/modules/reports/components/main/rows.jsx
- frontend/src/modules/reports/components/request/index.jsx
- frontend/src/modules/reports/components/request/styles.css
- frontend/src/modules/reports/reducer/filters.js
- frontend/src/modules/requests/components/request-form/form.jsx
- frontend/src/modules/requests/components/request-form/index.jsx
- frontend/src/modules/requests/components/request/details.jsx
- frontend/src/modules/requests/components/request/index.jsx
- frontend/src/modules/requests/components/request/request-type.jsx
- frontend/src/modules/requests/components/request/sidebar.jsx
- frontend/src/modules/requests/utils.js
- frontend/src/utils/index.js
Numerous changes to support proper labelling for import vs export requests and code vs data requests.
> Request type labelling

- .travis.yml
- ui_tests/Include/features/administrator/no_access_outside_proj.feature
- ui_tests/Include/features/administrator/no_access_to_unapproved.feature
- ui_tests/Include/scripts/groovy/test/ocwa/common/Constant.groovy
- ui_tests/Include/scripts/groovy/test/ocwa/common/Step.groovy
- ui_tests/Include/scripts/groovy/test/ocwa/features/LoginStep.groovy
- ui_tests/Include/scripts/groovy/test/ocwa/features/RequesterStep.groovy
- ui_tests/Include/scripts/groovy/test/ocwa/features/StateStep.groovy
- ui_tests/Scripts/Administrator/NoAccessOutsideProjTest/Script1564510605090.groovy
- ui_tests/Scripts/Administrator/NoAccessToUnapprovedTest/Script1564522497530.groovy
- ui_tests/Test Cases/Administrator/NoAccessOutsideProjTest.tc
- ui_tests/Test Cases/Administrator/NoAccessToUnapprovedTest.tc
- ui_tests/Test Suites/AccessSuite.groovy
- ui_tests/Test Suites/AccessSuite.ts
Adds access test suite.  Only runs on PRs.
See Gherkin feature files for what the tests are testing:
https://github.com/bcgov/OCWA/blob/feature/accesstests/ui_tests/Include/features/administrator/no_access_outside_proj.feature
https://github.com/bcgov/OCWA/blob/feature/accesstests/ui_tests/Include/features/administrator/no_access_to_unapproved.feature
> Feature/accesstests - adds access test suite integration tests

- frontend/package-lock.json
- frontend/package.json
- frontend/src/modules/download/components/requests/index.jsx
- frontend/src/modules/requests/components/request-form/form.jsx
Fixes a form focus problem where generating a list of fields to render in the node tree would cause a unexpected re-render. Also fix a incorrect title string (#197).
> Fix loss of focus issue when skipping the first field of a form

- frontend/src/modules/output-checker/components/request/sidebar.jsx
- frontend/src/modules/output-checker/reducer.js
Output Checker improvements: Remove the request revisions button from code requests (#193) and only show the approving dialog when an actual approve action is taken (#194).
> Fix OC UI State Issues

- frontend/src/modules/files/reducer/upload-status.js
Not saving a request after uploading a file would result in the uploading button to be stuck, this fixes that by reseting all upload statuses after a request component has been unmounted.
> Bust upload ghost

- frontend/src/modules/requests/components/request-menu/index.jsx
Enable duplication of denied and cancelled requests from list page.
> Enable duplicate request ability for denied and cancelled requests

- helm/ocwa/values.yaml
- microservices/requestApi/README.md
- microservices/requestApi/config/default.json.example
- microservices/requestApi/entrypoint.sh
- microservices/requestApi/helm/request-api/templates/deployment.yaml
- microservices/requestApi/helm/request-api/templates/requestApi-config-map.yaml
- microservices/requestApi/helm/request-api/values.yaml
- microservices/requestApi/notifications/email/emailSubmitTemplate.html
- microservices/requestApi/notifications/email/emailTemplate.html
- microservices/requestApi/notifications/email/index.js
Email tweaks, new template, new variable support better support different url definition types, url different for import vs export
Email tweaks, new template, new variable support better support different url definition types, url different for import vs export
> Email tweaks, new template, new variable support

- microservices/requestApi/auth/auth.js
- microservices/requestApi/db/model/request.js
Allow a supervisor to be able to access the OCWA reports from either inside the VPN or inside the SRE.  Unlike currently where the supervisor needs to log into the SRE for access.
> Update supervisor access to allow any zone

- README.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/modules/reports/components/request/index.jsx
- ui_tests/Include/features/administrator/no_access_outside_proj.feature
- ui_tests/Include/features/administrator/view_reports.feature
- ui_tests/Include/scripts/groovy/test/ocwa/common/Constant.groovy
- ui_tests/Include/scripts/groovy/test/ocwa/common/Utils.groovy
- ui_tests/Include/scripts/groovy/test/ocwa/features/LoginStep.groovy
- ui_tests/Include/scripts/groovy/test/ocwa/features/ReportStep.groovy
- ui_tests/Profiles/default.glbl
- ui_tests/Scripts/Administrator/ViewReports/Script1567630236297.groovy
- ui_tests/Test Cases/Administrator/ViewReports.tc
- ui_tests/Test Suites/HappyPathSuite.ts
Integration test the reports functionality
Tests the reports functionality.  Happy path only.  Focus is on testing a non-code export.  Checks chronology (state transitions) as well.
> Feature/report integ test - tests the reports functionality

- README.md
- frontend/.prettierrc
- frontend/README.md
- frontend/src/modules/data/components/data-request/index.jsx
Hopefully improved 2 areas of documentation, the Frontend and the root Quick Start READMEs. In the frontend the config values are explained in greater detail, along with some clarification in some areas and details on code structure. Regarding the Quick Start a few additional details were added that I ran into trying to run the app from root on a fresh machine.
> Updates to Documentation

- frontend/src/modules/requests/components/request/details-row.jsx
- frontend/src/modules/requests/components/request/details.jsx
Adds checkbox and radio button support to the read only request details view.
> Adjust the details component to be a little more polymorphic.

- frontend/src/modules/reports/containers/main.js
Lowered the minimum reported request state from 3 to 2.
> Switch reporting filter from reviewed requests to any submitted request.

- microservices/forumApi/routes/v1/routes/topics.js
> Fix topic creation failing with parent topic

- frontend/src/modules/output-checker/components/request/styles.css
Fixes some layout issues with the OC request details.
> Adjust request details layout in OC.
